# Generated by Django 4.1 on 2024-04-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мусор'), (2, 'Проходняк'), (3, 'Можно поиграть'), (4, 'Похвально'), (5, 'Изумительно')], null=True),
        ),
    ]
